# Generated by Django 4.1 on 2022-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
