# Generated by Django 4.1 on 2022-11-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0006_order_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
