# Generated by Django 4.1 on 2022-11-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0007_remove_order_cost_remove_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='stripe_payment.item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='stripe_payment.order')),
            ],
            options={
                'verbose_name': 'order_item',
                'verbose_name_plural': 'order_items',
                'ordering': ['id'],
            },
        ),
    ]
